# Generated by Django 5.2.8 on 2025-11-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_project_alter_writeup_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteUpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/writeups/')),
            ],
        ),
    ]
