# Generated by Django 5.2.8 on 2025-12-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_writeupimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='url',
            field=models.URLField(default='https://www.text.com', help_text='Challenge/Lab URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='writeupimage',
            name='image',
            field=models.ImageField(upload_to='writeups/'),
        ),
    ]
